# Generated by Django 3.1.2 on 2022-10-05 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_auto_20221001_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcropdetails',
            name='fid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.registration'),
        ),
        migrations.CreateModel(
            name='Loantype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestamount', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.registration')),
            ],
        ),
    ]
