# Generated by Django 3.1.2 on 2022-10-06 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_auto_20221005_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivaryboy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='requestamount',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='status',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='uid',
        ),
        migrations.AddField(
            model_name='loantype',
            name='amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loantype',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loantype',
            name='duration',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loantype',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Loanrequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestamount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('loanid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.loantype')),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='delivary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('cropid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.addcropdetails')),
                ('did', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.delivaryboy')),
            ],
        ),
    ]
