# Generated by Django 4.1.3 on 2023-04-18 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0006_registration_logid_alter_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivaryboy',
            name='logid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.login'),
        ),
    ]
